#!/usr/bin/env bash
# The script to check for dns records of domains
check_domain() {
	response=$(dig "$2.$1")
        subd="$2"
        ip=$(echo "$response" | awk "/^$subd/ {print \$5}")
        record=$(echo "$response" | awk "/^$subd/ {print \$4}")
        echo "The subdomain $2 is a $record record and points to $ip"
}
if [ "$2" ]; then
	check_domain "$1" "$2"
else
	check_domain "$1" "www"
	check_domain "$1" "lb-01"
	check_domain "$1" "web-01"
	check_domain "$1" "web-02"
fi
