#!/usr/bin/env bash
#script to install and configure nginx
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
header_config="
server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;
    location / {
    	add_header X-Served-By $HOSTNAME;
    }
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
"
sudo echo "$header_config" > /etc/nginx/sites-available/default
if pgrep nginx > /dev/null; then
	service nginx restart
else
	service nginx start
fi
