#!/usr/bin/env bash
#script to install and configure haproxy load balancer
sudo apt -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt -y update
sudo apt install haproxy -y
printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy
defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000
listen alx
    bind :80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 207136-web-01 100.26.173.25:80 check
    server 207136-web-02 52.91.123.57:80 check
" > /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
