#!/usr/bin/env bash
# a script to print To infinity and beyond indefinitely
function handle_sigterm {
	echo "I am invincible!!!"
}

trap handle_sigterm SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done
echo "I am invincible!!!"
