#!/usr/bin/env bash
#  Script for question 0
interfaces=$(ip link show | awk -F': ' '{print $2}')

# Loop through each interface and get its IPv4 address(es)
for interface in $interfaces; do
  ipv4_addresses=$(ip addr show $interface | awk '$1 == "inet" {print $2}')
  echo "$ipv4_addresses"
done
