#!/usr/bin/env bash
# script for configuring nginx
sed 's/80/8080/g' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/sites-available/default
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo -u nginx service nginx start
