#!/usr/bin/env bash
# script for configuring nginx
config="server {
    listen 80 default_server;
    listen 8080 default_server;
    listen [::]:80 default_server;
    listen [::]:8080 default_server;
    root /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}"
echo "$config" > /etc/nginx/sites-available/default
sudo service nginx reload
sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo adduser nginx

